### ISSUE TITLE
onChange or onDeleteComponent not triggered

### ISSUE THREAD

**Issue by aminmc** [formio/react-formio#198]
Hello,

Just noticed that if you remove a component from a form the onChange or even the onDeleteComponent callback is not invoked.  See:

https://codesandbox.io/s/react-example-gz9p3

Using 4.0.0-beta.16 (react-formio)
Using 4.0.0-beta-35 (formiojs)

**Comment by randallknutson** [comment]
The onChange should be working but it is possible that it isn't at the moment. We have it on our task list to go through these events before we do our final release and ensure they work correctly. We'd love to have some community help on this if you are able. Otherwise we'll be sure it works correctly before the final release.

**Comment by lukeburns** [comment]
Experiencing no onChange callback with 4.0.0-beta.29. Looks like there's a lot of active development happening. What is the development timeline for 4.0 release?

**Comment by randallknutson** [comment]
We are trying to get the 4.x branch into RC by the end of the month. It is stabilizing quickly but there is still lots of work to be done.

**Comment by lukeburns** [comment]
Ah, I misread the documentation. I thought I was supposed to be wrapping FormBuilder with FormEdit. FormBuilder alone does fire onChange callbacks.

**Comment by ivan-pik** [comment]
I made a PR https://github.com/formio/react-formio/pull/216

**Comment by limouren** [comment]
Hi @ivan-pik, your changes has been overwritten by fad22d8be15291a7a27a9bf8ca386c1da0caa4ba. I have sent #261 to fix that.
