### ISSUE TITLE
input-group on wrapping every component

### ISSUE THREAD

**Issue by batusai513** [formio/react-formio#27]
I'm having this issue where every component in the form is getting the input-group class, and that class is just for elements with prefix or sufix (or both), and when using bootstrap, the style is messed up.

**Comment by randallknutson** [comment]
We originally had it as you described but this caused a lot of issues with fields with a prefix or suffix inside of a datagrid or table since they have different box properties depending on whether they are in an input-group or not. To resolve this we always put them in an input-group and added some CSS to make it look better. See https://github.com/formio/react-formio/blob/master/formio.css#L3-L28

This may not be the best solution so let me know if you have any thoughts on it.
