### ISSUE TITLE
react-widgets styles

### ISSUE THREAD

**Issue by batusai513** [formio/react-formio#28]
Hey, one last thing (Hopefully), how do i add the styles for the react widgets components, is there an easy way, what would be the steps there?

**Comment by randallknutson** [comment]
Since the react-widgets library is installed, just add the CSS file any way you like. One way that works well is to add it with webpack with the proper loaders. I've done this in a sample react app.

https://github.com/formio/react-example/blob/master/src/app.jsx#L5-L6
https://github.com/formio/react-example/blob/master/webpack.config.js#L25-L28

If you go this route be sure to add css-loader and style-loader to package.json as well.

You can also manually include the file in your index.html file.
